In [1]:

from ib_insync import *

util.startLoop()

ib = IB()
ib.connect('host.docker.internal', 7497, clientId=15)

In [2]:
import qgrid
import functools
from collections import namedtuple
import pandas as pd

pd.set_option('display.max_colwidth',100)
start = ''
end = "20200828 11:41:41"
contract = Stock('SPY', 'SMART', 'USD')

ticks = ib.reqHistoricalTicks(contract, start, end, 1000, 'TRADES', useRth=False)
df = util.df(ticks)
df = df.set_index('time')
df = df.tz_convert('America/Toronto')

df['pastLimit'] = [row.pastLimit for row in df['tickAttribLast']]
df['unreported'] = [row.unreported for row in df['tickAttribLast']]
del df['tickAttribLast']
display(df)
ticks = ib.reqHistoricalTicks(contract, start, end, 1000, 'BID_ASK', useRth=False)
df = util.df(ticks)
df = df.set_index('time')
df = df.tz_convert('America/Toronto')
# display(df)
# print(df.dtypes)

df['bidPastLow'] = [row.bidPastLow for row in df['tickAttribBidAsk']]
df['askPastHigh'] = [row.askPastHigh for row in df['tickAttribBidAsk']]
del df['tickAttribBidAsk']
display(df)
# df.to_csv("tsla.csv")


end = "20200828 23:59:00"
bars = ib.reqHistoricalData(
    contract,endDateTime=end, durationStr='1 D',
    barSizeSetting='5 mins', whatToShow='TRADES', useRTH=False)
df = util.df(bars)
df = df.set_index('date')
display(df)

bars = ib.reqHistoricalData(
    contract,endDateTime=end, durationStr='1 D',
    barSizeSetting='5 mins', whatToShow='BID_ASK', useRTH=False)
df = util.df(bars)
df = df.set_index('date')
display(df)
bars = ib.reqHistoricalData(
    contract,endDateTime=end, durationStr='1 D',
    barSizeSetting='5 mins', whatToShow='MIDPOINT', useRTH=False)

df = util.df(bars)
df = df.set_index('date')

display(df)

##AZURE COSMOS DB or MONGO

,price,size,exchange,specialConditions,pastLimit,unreported
time,,,,,,
2020-08-28 11:38:51-04:00,349.1900,2,ISLAND,I,False,True
2020-08-28 11:38:51-04:00,349.2000,4,ISLAND,F I,False,True
2020-08-28 11:38:51-04:00,349.1975,4,FINRA,I,False,True
2020-08-28 11:38:51-04:00,349.2000,20,FINRA,I,False,True
2020-08-28 11:38:51-04:00,349.2000,7,ISLAND,I,False,True
...,...,...,...,...,...,...
2020-08-28 11:41:39-04:00,349.1000,100,BATS,F,False,False
2020-08-28 11:41:39-04:00,349.1000,24,ISLAND,F I,False,True
2020-08-28 11:41:39-04:00,349.1001,1,FINRA,I,False,True
2020-08-28 11:41:40-04:00,349.1000,3,BYX,I,False,True
2020-08-28 11:41:40-04:00,349.1200,6,ARCA,I,False,True

,priceBid,priceAsk,sizeBid,sizeAsk,bidPastLow,askPastHigh
time,,,,,,
2020-08-28 11:41:36-04:00,349.12,349.13,100,2500,False,False
2020-08-28 11:41:37-04:00,349.12,349.13,300,2500,False,False
2020-08-28 11:41:37-04:00,349.12,349.13,300,2600,False,False
2020-08-28 11:41:37-04:00,349.12,349.13,300,2700,False,False
2020-08-28 11:41:37-04:00,349.12,349.13,300,2800,False,False
...,...,...,...,...,...,...
2020-08-28 11:41:40-04:00,349.10,349.12,2300,4100,False,False
2020-08-28 11:41:40-04:00,349.10,349.12,2300,4000,False,False
2020-08-28 11:41:40-04:00,349.10,349.12,2300,3800,False,False
2020-08-28 11:41:40-04:00,349.10,349.12,2300,3700,False,False
2020-08-28 11:41:40-04:00,349.10,349.12,2400,3700,False,False

                       open    high     low   close  volume  average  barCount
date
2020-08-28 04:00:00  349.26  349.43  349.26  349.43       8  349.343         5
2020-08-28 04:05:00  349.48  349.48  349.43  349.43      26  349.435         7
2020-08-28 04:10:00  349.46  349.48  349.43  349.48      39  349.441        10
2020-08-28 04:15:00  349.55  349.79  349.55  349.79     126  349.657        49
2020-08-28 04:20:00  349.75  350.02  349.75  350.02      53  349.881        18
...                     ...     ...     ...     ...     ...      ...       ...
2020-08-28 19:35:00  350.94  350.96  350.92  350.95      18  350.950         8
2020-08-28 19:40:00  350.94  350.98  350.94  350.96      48  350.962        13
2020-08-28 19:45:00  350.96  350.96  350.96  350.96      13  350.960         5
2020-08-28 19:50:00  350.95  351.03  350.95  351.00      68  351.003        17
2020-08-28 19:55:00  351.03  351.03  350.98  350.98      38  351.003        14

[192 rows x 7 columns]

                       open    high     low   close  volume  average  barCount
date
2020-08-28 04:00:00  349.25  349.98  348.26  349.32      -1     -1.0        -1
2020-08-28 04:05:00  349.44  349.59  349.33  349.50      -1     -1.0        -1
2020-08-28 04:10:00  349.46  349.62  349.35  349.49      -1     -1.0        -1
2020-08-28 04:15:00  349.67  349.83  349.51  349.70      -1     -1.0        -1
2020-08-28 04:20:00  349.83  350.08  349.68  349.86      -1     -1.0        -1
...                     ...     ...     ...     ...     ...      ...       ...
2020-08-28 19:35:00  350.92  350.96  350.91  350.95      -1     -1.0        -1
2020-08-28 19:40:00  350.94  350.99  350.91  350.98      -1     -1.0        -1
2020-08-28 19:45:00  350.93  350.99  350.93  350.97      -1     -1.0        -1
2020-08-28 19:50:00  350.96  351.03  350.95  351.00      -1     -1.0        -1
2020-08-28 19:55:00  350.98  351.03  350.94  351.01      -1     -1.0        -1

[192 rows x 7 columns]

,open,high,low,close,volume,average,barCount
date,,,,,,,
2020-08-28 04:00:00,349.120,349.455,349.120,349.405,-1,-1.0,-1
2020-08-28 04:05:00,349.405,349.555,349.355,349.445,-1,-1.0,-1
2020-08-28 04:10:00,349.445,349.590,349.375,349.530,-1,-1.0,-1
2020-08-28 04:15:00,349.530,349.805,349.525,349.760,-1,-1.0,-1
2020-08-28 04:20:00,349.760,350.055,349.690,350.030,-1,-1.0,-1
...,...,...,...,...,...,...,...
2020-08-28 19:35:00,350.925,350.955,350.915,350.935,-1,-1.0,-1
2020-08-28 19:40:00,350.935,350.980,350.925,350.950,-1,-1.0,-1
2020-08-28 19:45:00,350.950,350.975,350.945,350.970,-1,-1.0,-1
2020-08-28 19:50:00,350.970,351.025,350.965,351.015,-1,-1.0,-1
2020-08-28 19:55:00,351.015,351.015,350.970,350.985,-1,-1.0,-1

In [3]:
from datetime import datetime as dt, timedelta as td
contract = Stock('SPY', 'SMART', 'USD')
# def getTicks(date):
date = dt.now()
start = ''
end = "20200828 11:41:41"

In [4]:
start = ''
end = "20200904 16:00:00"
contract = Stock('SPY', 'SMART', 'USD')
def qryHistTicks(contract,dtstr,nticks=1000,mode='end'):
    df = pd.DataFrame()
    if mode == 'end':
        start = ''
        end = f'{dtstr}'
    else:
        start = f'{dtstr}'
        end = ''
    try:
        ticks = ib.reqHistoricalTicks(contract, start, end, nticks, 'TRADES', useRth=False)
        df = util.df(ticks)
        df = df.set_index('time')
        df = df.tz_convert('America/Toronto')
        df['pastLimit'] = [row.pastLimit for row in df['tickAttribLast']]
        df['unreported'] = [row.unreported for row in df['tickAttribLast']]
        del df['tickAttribLast']
    except Exception as e: print(e)
    size = len(df)
    first = df.index[0]
    last = df.index[-1]
    nextm = None

    if mode == 'end': 
        display(first)
        nex = first + td(seconds=0)
        df = df[df.index != first]
    else: 
        nex = last - td(seconds=0)
        df = df[df.index != last]
    nextm = nex.strftime("%Y%m%d %H:%M:%S")
    
    return df,nextm

df_full = pd.DataFrame()
df,next_time = qryHistTicks(contract,"20200828 23:59:99",mode='end')
while next_time != None:
    print("going ",next_time)
    df,next_time = qryHistTicks(contract,next_time,mode='end')
    df_full = df_full.append(df)

Timestamp('2020-08-28 18:12:57-0400', tz='America/Toronto')

going  20200828 18:12:57

Timestamp('2020-08-28 17:03:18-0400', tz='America/Toronto')

going  20200828 17:03:18

Timestamp('2020-08-28 16:29:56-0400', tz='America/Toronto')

going  20200828 16:29:56

Timestamp('2020-08-28 16:11:19-0400', tz='America/Toronto')

going  20200828 16:11:19

Timestamp('2020-08-28 16:06:23-0400', tz='America/Toronto')

going  20200828 16:06:23

Timestamp('2020-08-28 16:02:47-0400', tz='America/Toronto')

going  20200828 16:02:47

KeyboardInterrupt:

In [6]:
df_full.to_csv('SPY_tape_sample.csv')

In [3]:
import asyncio, asyncpg, os, nest_asyncio
nest_asyncio.apply()

async def execSQL(qry):
    conn = await asyncpg.connect(user="postgres",password="FoolishPassword",database='stocks',host='postgres',port='5432',)
    await conn.execute(f'''{qry}''')
    await conn.close()

async def copyDF(df,schema,table):
    conn = await asyncpg.connect(user="postgres",password="FoolishPassword",database='stocks',host='postgres',port='5432',)
    await conn.execute(f'''SET search_path TO {schema};''')
    tuples = list(df.itertuples(index=True, name=None))
    li=list(df.columns)
    li.insert(0,df.index.name)
    display(tuples)
    await conn.copy_records_to_table(table, records=tuples, columns=li, timeout=10)
    await conn.close()



s = f'CREATE SCHEMA IF NOT EXISTS "GE" AUTHORIZATION postgres;'
asyncio.get_event_loop().run_until_complete(execSQL(s))

# s = await conn.copy_records_to_table(table_name, records=tuples, columns=list(df.columns), timeout=10)

In [84]:

display(li)

['date', 'open', 'high', 'low', 'close', 'volume', 'average', 'barcount']

In [23]:
end = "20200904 23:59:00"
histbarExample = ['1 D','5 secs','TRADES']
def histBar(endt,dStr,bSize,show,useRTH=False):
    bars = ib.reqHistoricalData(
        contract,endDateTime=end, durationStr=f'{dStr}',
        barSizeSetting=f'{bSize}', whatToShow=f'{show}', useRTH=useRTH)
    df = util.df(bars)
    df = df.set_index('date')
    df.columns = map(str.lower, df.columns)
    return df

df = histBar(end,histbarExample[0],histbarExample[1],histbarExample[2])
display(df)
df.to_csv('SPY_bar_sample_5sec.csv')
asyncio.get_event_loop().run_until_complete(copyDF(df,'spy','d1'))

                       open    high     low   close  volume  average  barcount
date
2020-09-04 04:00:00  347.00  347.00  346.86  346.89      81  346.989         4
2020-09-04 04:00:05  346.89  346.89  346.89  346.89       0  346.890         0
2020-09-04 04:00:10  346.89  346.89  346.89  346.89       0  346.890         0
2020-09-04 04:00:15  347.00  347.00  347.00  347.00       1  347.000         1
2020-09-04 04:00:20  347.00  347.00  347.00  347.00       0  347.000         0
...                     ...     ...     ...     ...     ...      ...       ...
2020-09-04 19:59:35  341.99  341.99  341.99  341.99       0  341.990         0
2020-09-04 19:59:40  342.00  342.00  342.00  342.00       1  342.000         1
2020-09-04 19:59:45  342.00  342.00  342.00  342.00       0  342.000         0
2020-09-04 19:59:50  342.00  342.00  342.00  342.00       0  342.000         0
2020-09-04 19:59:55  342.00  342.00  342.00  342.00       0  342.000         0

[11520 rows x 7 columns]

NameError: name 'asyncio' is not defined

In [32]:
end = "20200904 23:59:00"
stock,bss = "NVDA",'15 secs'
bss_trim = bss.replace(' ','')
contract = Stock(stock, 'SMART', 'USD')

he = ['1 D','5 secs','TRADES']
def histBar(endt,dStr,bSize,show,useRTH=False):
    bars = ib.reqHistoricalData(
        contract,endDateTime=end, durationStr=f'{dStr}',
        barSizeSetting=f'{bSize}', whatToShow=f'{show}', useRTH=useRTH)
    df = util.df(bars)
    df = df.set_index('date')
    df.columns = map(str.lower, df.columns)
    return df
df = histBar(end,he[0],bss,"TRADES",useRTH=False)

display(df)
df.to_csv(f'{stock}_bar_sample_{bss_trim}.csv')

                       open    high     low   close  volume  average  barcount
date
2020-09-04 04:00:00  512.00  512.00  512.00  512.00      20  512.000         2
2020-09-04 04:00:15  512.00  512.00  512.00  512.00       0  512.000         0
2020-09-04 04:00:30  512.98  512.98  512.98  512.98       1  512.980         1
2020-09-04 04:00:45  512.98  512.98  512.98  512.98       0  512.980         0
2020-09-04 04:01:00  513.87  513.90  513.87  513.90       2  513.882         2
...                     ...     ...     ...     ...     ...      ...       ...
2020-09-04 19:58:45  499.52  499.52  499.52  499.52       0  499.520         0
2020-09-04 19:59:00  499.52  499.52  499.52  499.52       0  499.520         0
2020-09-04 19:59:15  499.60  499.60  499.55  499.55       2  499.575         2
2020-09-04 19:59:30  499.55  499.55  499.55  499.55       0  499.550         0
2020-09-04 19:59:45  499.55  499.55  499.55  499.55       0  499.550         0

[3840 rows x 7 columns]